packages:
  - 'apps/*'
  - 'packages/*'
  - 'toolings/*'

catalog:
  # Dev tooling
  typescript: ^5.8.2
  eslint: ^9.23.0
  prettier: ^3.5.3

  # Misc
  zod: ^3.24.2
  'dotenv-cli': ^8.0.0
  'use-intl': ^4.0.2
  'next-themes': ^0.4.4
  'next-intl': ^4.0.2
  'lucide-react': ^0.475.0

  # Types
  '@types/node': ^22.13.11

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.0.12
    '@types/react-dom': ^19.0.4
